### ISSUE TITLE
Fuzzing the module an error was flaged

### ISSUE THREAD

**Issue by ktfth** [willgm/web-crypto-storage#11]
#0 READ units: 1
=================================================================
ReferenceError: window is not defined
    at getCryptoObject (/home/kaique/war/web-crypto-storage-fuzzing/node_modules/@webcrypto/storage/dist/web-crypto-storage.cjs.js:1:70986)
    at generateHash (/home/kaique/war/web-crypto-storage-fuzzing/node_modules/@webcrypto/storage/dist/web-crypto-storage.cjs.js:1:75728)
    at CryptoStorage.<anonymous> (/home/kaique/war/web-crypto-storage-fuzzing/node_modules/@webcrypto/storage/dist/web-crypto-storage.cjs.js:1:90917)
    at step (/home/kaique/war/web-crypto-storage-fuzzing/node_modules/@webcrypto/storage/dist/web-crypto-storage.cjs.js:1:70441)
    at Object.next (/home/kaique/war/web-crypto-storage-fuzzing/node_modules/@webcrypto/storage/dist/web-crypto-storage.cjs.js:1:67486)
    at /home/kaique/war/web-crypto-storage-fuzzing/node_modules/@webcrypto/storage/dist/web-crypto-storage.cjs.js:1:66765
    at new Promise (<anonymous>)
    at __awaiter (/home/kaique/war/web-crypto-storage-fuzzing/node_modules/@webcrypto/storage/dist/web-crypto-storage.cjs.js:1:65972)
    at CryptoStorage.set (/home/kaique/war/web-crypto-storage-fuzzing/node_modules/@webcrypto/storage/dist/web-crypto-storage.cjs.js:1:90532)
    at Worker.fuzz [as fn] (/home/kaique/war/web-crypto-storage-fuzzing/fuzz.js:1:1333)
crash was written to crash-e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
crash(hex)=
Worker exited

**Comment by willgm** [comment]
Hello @ktfth!

As we discussed by pm, I need more details about witch command were you running, which version of NodeJS, npm and etc.

I gonna close this issue until you give more details, then we can reopen.

Until then I will make a issue template to guide the next open issues.

Thanks,
William
